# Generated by Django 3.1.7 on 2021-11-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='relate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.cron'),
            preserve_default=False,
        ),
    ]
