# Generated by Django 3.1.7 on 2021-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20211122_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='comments',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
