# Generated by Django 3.1.7 on 2021-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_cron_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='comments',
            field=models.CharField(default='备注', max_length=200),
        ),
    ]
