# Generated by Django 3.1.7 on 2021-12-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_ip', models.CharField(max_length=50)),
                ('cron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.cron')),
            ],
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
