# Generated by Django 3.1.7 on 2021-12-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20211206_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BkIp',
            new_name='Address',
        ),
    ]
