# Generated by Django 3.1.7 on 2021-12-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20211207_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cron',
        ),
        migrations.AddField(
            model_name='cron',
            name='bkip',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.address'),
            preserve_default=False,
        ),
    ]
