# Generated by Django 3.1.7 on 2021-12-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20211207_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='bkip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.address'),
        ),
    ]
